export const projectGalleries = [
  [
    "https://cdn.poehali.dev/files/веретье0.jpg",
    "https://cdn.poehali.dev/files/веретье1.JPG",
    "https://cdn.poehali.dev/files/веретье2.JPG",
    "https://cdn.poehali.dev/files/веретье3.JPG",
    "https://cdn.poehali.dev/files/веретье5.jpg",
    "https://cdn.poehali.dev/files/веретье6.JPG",
    "https://cdn.poehali.dev/files/веретье7.JPG",
    "https://cdn.poehali.dev/files/веретье8.JPG",
    "https://cdn.poehali.dev/files/веретье9.JPG",
    "https://cdn.poehali.dev/files/веретье10.JPG",
    "https://cdn.poehali.dev/files/веретье11.JPG",
    "https://cdn.poehali.dev/files/веретье12.jpg",
    "https://cdn.poehali.dev/files/веретье13.JPG",
    "https://cdn.poehali.dev/files/веретье14.JPG",
    "https://cdn.poehali.dev/files/веретье15.JPG",
    "https://cdn.poehali.dev/files/веретье16.JPG",
    "https://cdn.poehali.dev/files/веретье17.JPG",
    "https://cdn.poehali.dev/files/веретье18.JPG",
    "https://cdn.poehali.dev/files/веретье19.JPG",
    "https://cdn.poehali.dev/files/веретье20.JPG",
    "https://cdn.poehali.dev/files/веретье21.JPG",
    "https://cdn.poehali.dev/files/веретье22.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/1.JPG",
    "https://cdn.poehali.dev/files/2.JPG",
    "https://cdn.poehali.dev/files/3.JPG",
    "https://cdn.poehali.dev/files/4.JPG",
    "https://cdn.poehali.dev/files/5.JPG",
    "https://cdn.poehali.dev/files/6.JPG",
    "https://cdn.poehali.dev/files/7.JPG",
    "https://cdn.poehali.dev/files/8.JPG",
    "https://cdn.poehali.dev/files/9.JPG",
    "https://cdn.poehali.dev/files/10.JPG",
    "https://cdn.poehali.dev/files/11.JPG",
    "https://cdn.poehali.dev/files/12.JPG",
    "https://cdn.poehali.dev/files/13.JPG",
    "https://cdn.poehali.dev/files/14.JPG",
    "https://cdn.poehali.dev/files/15.JPG",
    "https://cdn.poehali.dev/files/16.JPG",
    "https://cdn.poehali.dev/files/17.JPG",
    "https://cdn.poehali.dev/files/18.JPG",
    "https://cdn.poehali.dev/files/19.JPG",
    "https://cdn.poehali.dev/files/20.JPG",
    "https://cdn.poehali.dev/files/21.JPG",
    "https://cdn.poehali.dev/files/22.JPG",
    "https://cdn.poehali.dev/files/23.JPG",
    "https://cdn.poehali.dev/files/24.JPG",
    "https://cdn.poehali.dev/files/25.JPG",
    "https://cdn.poehali.dev/files/26.JPG",
    "https://cdn.poehali.dev/files/27.JPG",
    "https://cdn.poehali.dev/files/28.JPG",
    "https://cdn.poehali.dev/files/29.JPG",
    "https://cdn.poehali.dev/files/30.JPG",
    "https://cdn.poehali.dev/files/31.JPG",
    "https://cdn.poehali.dev/files/32.JPG",
    "https://cdn.poehali.dev/files/33.JPG",
    "https://cdn.poehali.dev/files/34.JPG",
    "https://cdn.poehali.dev/files/35.JPG",
    "https://cdn.poehali.dev/files/36.JPG",
    "https://cdn.poehali.dev/files/37.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/e145e902-0d5a-4598-9062-6395356985f0.jpg",
    "https://cdn.poehali.dev/files/44a34322-94c4-4927-b372-e632bd76e8c3.png",
    "https://cdn.poehali.dev/files/7c45af13-f389-40c5-a0ec-e0bed1884fef.jpg",
    "https://cdn.poehali.dev/files/cfa7f22e-7434-41a8-83cb-57c58472a187.jpg",
    "https://cdn.poehali.dev/files/0d1e0e9b-67ef-4b9f-8a21-913de4d4c829.jpg",
    "https://cdn.poehali.dev/files/4b438963-c14c-4a31-a4f6-dddd9a791e0c.jpg",
    "https://cdn.poehali.dev/files/6c712b7d-0a01-41fe-89c1-29ec45bad1dd.jpg",
    "https://cdn.poehali.dev/files/2025-10-24 11-58-47.JPG",
    "https://cdn.poehali.dev/files/2025-10-28 15-44-24.JPG",
    "https://cdn.poehali.dev/files/2025-10-28 15-44-38.JPG",
    "https://cdn.poehali.dev/files/2025-10-30 11-43-00.JPG",
    "https://cdn.poehali.dev/files/2025-10-30 11-43-04.JPG",
    "https://cdn.poehali.dev/files/2025-11-01 11-49-37.JPG",
    "https://cdn.poehali.dev/files/2025-11-03 15-30-21.JPG",
    "https://cdn.poehali.dev/files/2025-11-13 15-15-33.JPG",
    "https://cdn.poehali.dev/files/IMG_20260105_110725.jpg",
    "https://cdn.poehali.dev/files/IMG_20260105_110740.jpg",
    "https://cdn.poehali.dev/files/IMG_20260105_110835.jpg",
    "https://cdn.poehali.dev/files/IMG_20260105_111100.jpg",
    "https://cdn.poehali.dev/files/photo_2025-12-05_20-09-38.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/01.JPG",
    "https://cdn.poehali.dev/files/02.JPG",
    "https://cdn.poehali.dev/files/03.JPG",
    "https://cdn.poehali.dev/files/04.JPG",
    "https://cdn.poehali.dev/files/05.JPG",
    "https://cdn.poehali.dev/files/06.JPG",
    "https://cdn.poehali.dev/files/07.JPG",
    "https://cdn.poehali.dev/files/08.JPG",
    "https://cdn.poehali.dev/files/09.JPG",
    "https://cdn.poehali.dev/files/010.JPG",
    "https://cdn.poehali.dev/files/011.JPG",
    "https://cdn.poehali.dev/files/012.JPG",
    "https://cdn.poehali.dev/files/013.JPG",
    "https://cdn.poehali.dev/files/014.JPG",
    "https://cdn.poehali.dev/files/015.JPG",
    "https://cdn.poehali.dev/files/016.JPG",
    "https://cdn.poehali.dev/files/017.JPG",
    "https://cdn.poehali.dev/files/018.JPG",
    "https://cdn.poehali.dev/files/019.JPG",
    "https://cdn.poehali.dev/files/020.JPG",
    "https://cdn.poehali.dev/files/021.JPG",
    "https://cdn.poehali.dev/files/022.JPG",
    "https://cdn.poehali.dev/files/023.JPG",
    "https://cdn.poehali.dev/files/024.JPG",
    "https://cdn.poehali.dev/files/025.JPG",
    "https://cdn.poehali.dev/files/026.JPG",
    "https://cdn.poehali.dev/files/027.JPG",
    "https://cdn.poehali.dev/files/028.JPG",
    "https://cdn.poehali.dev/files/029.JPG",
    "https://cdn.poehali.dev/files/030.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/photo_2025-12-29_10-41-49.jpg",
    "https://cdn.poehali.dev/files/2025-08-19 16-17-16.JPG",
    "https://cdn.poehali.dev/files/2025-07-21 09-57-59.JPG",
    "https://cdn.poehali.dev/files/2025-07-21 11-54-58.JPG",
    "https://cdn.poehali.dev/files/2025-07-21 12-47-59.JPG",
    "https://cdn.poehali.dev/files/2025-10-01 14-53-09.JPG",
    "https://cdn.poehali.dev/files/2451e998-d599-4eeb-8bf3-8585ffab4342.jpg",
    "https://cdn.poehali.dev/files/48198ca6-3425-4781-aba7-849426247fc4.jpg",
    "https://cdn.poehali.dev/files/1f94dc5e-69ba-4805-8f4b-ca5bbf6a404c.jpg",
    "https://cdn.poehali.dev/files/e9474b80-69ae-4a00-8574-c27200bb57ba.jpg",
    "https://cdn.poehali.dev/files/1d9d6ed2-45ec-4f8f-a51f-bc5915cdd76a.jpg",
    "https://cdn.poehali.dev/files/2025-09-30 13-06-25.JPEG",
    "https://cdn.poehali.dev/files/2025-09-30 13-06-37.JPEG",
    "https://cdn.poehali.dev/files/2025-10-15 14-56-54.JPG",
    "https://cdn.poehali.dev/files/2025-10-31 15-12-02.JPG",
    "https://cdn.poehali.dev/files/2025-10-17 15-58-24.JPG",
    "https://cdn.poehali.dev/files/2025-08-04 09-41-10.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/001.JPG",
    "https://cdn.poehali.dev/files/002.JPEG",
    "https://cdn.poehali.dev/files/003.JPG",
    "https://cdn.poehali.dev/files/004.JPG",
    "https://cdn.poehali.dev/files/005.JPG",
    "https://cdn.poehali.dev/files/006.JPG",
    "https://cdn.poehali.dev/files/007.JPG",
    "https://cdn.poehali.dev/files/008.JPG",
    "https://cdn.poehali.dev/files/009.JPG",
    "https://cdn.poehali.dev/files/0010.JPG",
    "https://cdn.poehali.dev/files/0011.JPG",
    "https://cdn.poehali.dev/files/0012.JPG",
    "https://cdn.poehali.dev/files/0013.JPEG",
    "https://cdn.poehali.dev/files/0014.JPG",
    "https://cdn.poehali.dev/files/0015.JPG",
    "https://cdn.poehali.dev/files/0016.JPG",
    "https://cdn.poehali.dev/files/0017.JPG",
    "https://cdn.poehali.dev/files/0018.JPG",
    "https://cdn.poehali.dev/files/0019.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/cca216a7-9b9e-425b-b0e4-d352cea5b6a4.png",
    "https://cdn.poehali.dev/files/aec4a2ca-0cc4-45f5-8a1f-76001cdb8530.png",
    "https://cdn.poehali.dev/files/84798a93-dd08-41eb-b20d-1a3611acf1be.png",
    "https://cdn.poehali.dev/files/61280d11-4eee-40f4-9105-3a20b63619e0.jpg",
    "https://cdn.poehali.dev/files/7062d1f4-7309-472d-bc60-6819f57dbd2f.png",
    "https://cdn.poehali.dev/files/35c2929b-6726-4db3-aa64-52835d7f9c45.jpg",
    "https://cdn.poehali.dev/files/9a264058-2d14-4695-bd33-455d0d97aad9.png",
    "https://cdn.poehali.dev/files/5b94e280-3e52-4724-9d15-ffe56a2b6bad.png",
    "https://cdn.poehali.dev/files/0c49f489-1f6b-4479-8142-3603d899660a.png",
    "https://cdn.poehali.dev/files/0b03e8cf-ef69-475b-a180-72929c4813b6.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/301.jpg",
    "https://cdn.poehali.dev/files/302.jpg",
    "https://cdn.poehali.dev/files/303.jpg",
    "https://cdn.poehali.dev/files/304.jpg",
    "https://cdn.poehali.dev/files/305.jpg",
    "https://cdn.poehali.dev/files/306.jpg",
    "https://cdn.poehali.dev/files/307.jpg",
    "https://cdn.poehali.dev/files/308.jpg",
    "https://cdn.poehali.dev/files/309.jpg",
    "https://cdn.poehali.dev/files/310.jpg",
    "https://cdn.poehali.dev/files/311.JPG",
    "https://cdn.poehali.dev/files/312.JPG",
    "https://cdn.poehali.dev/files/313.JPG",
    "https://cdn.poehali.dev/files/314.JPG",
    "https://cdn.poehali.dev/files/315.JPG",
    "https://cdn.poehali.dev/files/316.JPG",
    "https://cdn.poehali.dev/files/317.JPG",
    "https://cdn.poehali.dev/files/318.JPG",
    "https://cdn.poehali.dev/files/319.JPG",
    "https://cdn.poehali.dev/files/320.JPG",
    "https://cdn.poehali.dev/files/321.JPG",
    "https://cdn.poehali.dev/files/322.JPG",
    "https://cdn.poehali.dev/files/333.JPG",
    "https://cdn.poehali.dev/files/334.JPG",
    "https://cdn.poehali.dev/files/335.JPG",
    "https://cdn.poehali.dev/files/336.JPG",
    "https://cdn.poehali.dev/files/337.JPG",
    "https://cdn.poehali.dev/files/338.JPG",
    "https://cdn.poehali.dev/files/339.JPG",
    "https://cdn.poehali.dev/files/340.JPG",
    "https://cdn.poehali.dev/files/301.jpg",
    "https://cdn.poehali.dev/files/341.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/400.JPG",
    "https://cdn.poehali.dev/files/402.JPG",
    "https://cdn.poehali.dev/files/403.JPG",
    "https://cdn.poehali.dev/files/404.JPG",
    "https://cdn.poehali.dev/files/405.JPG",
    "https://cdn.poehali.dev/files/406.JPG",
    "https://cdn.poehali.dev/files/407.JPG",
    "https://cdn.poehali.dev/files/408.JPG",
    "https://cdn.poehali.dev/files/409.JPG",
    "https://cdn.poehali.dev/files/410.JPG",
    "https://cdn.poehali.dev/files/411.JPG",
    "https://cdn.poehali.dev/files/412.JPG",
    "https://cdn.poehali.dev/files/413.JPG",
    "https://cdn.poehali.dev/files/414.JPG",
    "https://cdn.poehali.dev/files/415.JPG",
    "https://cdn.poehali.dev/files/416.JPG",
    "https://cdn.poehali.dev/files/417.JPG",
    "https://cdn.poehali.dev/files/418.JPG",
    "https://cdn.poehali.dev/files/419.JPG",
    "https://cdn.poehali.dev/files/420.JPG",
    "https://cdn.poehali.dev/files/421.JPG",
    "https://cdn.poehali.dev/files/422.JPG",
    "https://cdn.poehali.dev/files/423.JPG",
    "https://cdn.poehali.dev/files/424.JPG",
    "https://cdn.poehali.dev/files/425.JPG",
    "https://cdn.poehali.dev/files/426.JPG",
    "https://cdn.poehali.dev/files/427.JPG",
    "https://cdn.poehali.dev/files/428.JPG",
    "https://cdn.poehali.dev/files/429.JPG",
    "https://cdn.poehali.dev/files/430.JPG",
    "https://cdn.poehali.dev/files/431.JPG",
    "https://cdn.poehali.dev/files/432.JPG",
    "https://cdn.poehali.dev/files/433.JPG",
    "https://cdn.poehali.dev/files/434.JPG",
    "https://cdn.poehali.dev/files/435.JPG",
    "https://cdn.poehali.dev/files/436.JPG",
    "https://cdn.poehali.dev/files/437.JPG",
    "https://cdn.poehali.dev/files/438.JPG",
    "https://cdn.poehali.dev/files/439.JPG",
    "https://cdn.poehali.dev/files/440.JPG",
    "https://cdn.poehali.dev/files/441.JPG",
    "https://cdn.poehali.dev/files/442.JPG",
    "https://cdn.poehali.dev/files/443.JPG",
    "https://cdn.poehali.dev/files/444.JPG",
    "https://cdn.poehali.dev/files/445.JPG",
    "https://cdn.poehali.dev/files/446.JPG",
    "https://cdn.poehali.dev/files/447.JPG",
    "https://cdn.poehali.dev/files/448.JPG",
    "https://cdn.poehali.dev/files/449.JPG",
    "https://cdn.poehali.dev/files/450.JPG",
    "https://cdn.poehali.dev/files/451.JPG",
    "https://cdn.poehali.dev/files/452.JPG",
    "https://cdn.poehali.dev/files/453.JPG",
    "https://cdn.poehali.dev/files/454.JPG",
    "https://cdn.poehali.dev/files/455.JPG",
    "https://cdn.poehali.dev/files/456.JPG",
    "https://cdn.poehali.dev/files/457.JPG",
    "https://cdn.poehali.dev/files/458.JPG",
    "https://cdn.poehali.dev/files/459.JPG",
    "https://cdn.poehali.dev/files/460.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/600.jpg",
    "https://cdn.poehali.dev/files/601.jpg",
    "https://cdn.poehali.dev/files/602.jpg",
    "https://cdn.poehali.dev/files/603.jpg",
    "https://cdn.poehali.dev/files/604.jpg",
    "https://cdn.poehali.dev/files/605.jpg",
    "https://cdn.poehali.dev/files/606.jpg",
    "https://cdn.poehali.dev/files/607.jpg",
    "https://cdn.poehali.dev/files/608.jpg",
    "https://cdn.poehali.dev/files/609.jpg",
    "https://cdn.poehali.dev/files/610.jpg",
    "https://cdn.poehali.dev/files/611.jpg",
    "https://cdn.poehali.dev/files/612.jpg",
    "https://cdn.poehali.dev/files/613.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/500.jpg",
    "https://cdn.poehali.dev/files/501.jpg",
    "https://cdn.poehali.dev/files/502.jpg",
    "https://cdn.poehali.dev/files/503.jpg",
    "https://cdn.poehali.dev/files/504.jpg",
    "https://cdn.poehali.dev/files/505.jpg",
    "https://cdn.poehali.dev/files/506.jpg",
    "https://cdn.poehali.dev/files/507.jpg",
    "https://cdn.poehali.dev/files/508.jpg",
    "https://cdn.poehali.dev/files/509.jpg",
    "https://cdn.poehali.dev/files/510.jpg",
    "https://cdn.poehali.dev/files/511.jpg",
    "https://cdn.poehali.dev/files/512.jpg",
    "https://cdn.poehali.dev/files/513.jpg",
    "https://cdn.poehali.dev/files/514.jpg",
    "https://cdn.poehali.dev/files/515.jpg"
  ]
];

export interface Project {
  img: string;
  title: string;
  size: string;
  material: string;
  location: string;
}

export const projects: Project[] = [
  {
    img: "https://cdn.poehali.dev/files/веретье0.jpg",
    title: "Баня из бревна 6×12",
    size: "6×12 м",
    material: "Оцилиндрованное бревно",
    location: 'Резиденция "Веретье", Пермский край'
  },
  {
    img: "https://cdn.poehali.dev/files/1.JPG",
    title: "Баня из бруса 8×15",
    size: "8×15 м",
    material: "Профилированный брус",
    location: "п. Полазна, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/IMG_20260105_110740.jpg",
    title: "Баня из бревна 3×6",
    size: "3×6 м",
    material: "Оцилиндрованное бревно",
    location: "д. Гамы, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/01.JPG",
    title: "Баня из бруса 10×10",
    size: "10×10 м",
    material: "Клееный брус",
    location: "д. Ключи, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/photo_2025-12-29_10-41-49.jpg",
    title: "Баня из бревна 6×6",
    size: "6×6 м",
    material: "Ремонт парной и помывочной",
    location: "д. Скобелевка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/001.JPG",
    title: "Баня из бревна 6×6",
    size: "6×6 м",
    material: "Шлифовка и покраска наружных стен",
    location: "д. Красная Слудка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/cca216a7-9b9e-425b-b0e4-d352cea5b6a4.png",
    title: "Баня из бруса 6×6",
    size: "6×6 м",
    material: "Профилированный брус",
    location: "д. Красная Слудка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/301.jpg",
    title: "Баня из бруса 6×8",
    size: "6×8 м",
    material: "Брус естественной влажности",
    location: "г. Добрянка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/400.JPG",
    title: "Баня из бревна 5×5",
    size: "5×5 м",
    material: "Оцилиндрованное бревно",
    location: "п. Усть-Качка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/600.jpg",
    title: "Баня из бревна 6×5",
    size: "6×5 м",
    material: "Рубленное бревно",
    location: "п. Троица, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/500.jpg",
    title: "Баня из бревна 6×8",
    size: "6×8 м",
    material: "Оцилиндрованное бревно",
    location: "д. Налимиха, Пермский край"
  }
];