export const projectGalleries = [
  [
    "https://cdn.poehali.dev/files/веретье0.jpg",
    "https://cdn.poehali.dev/files/веретье1.JPG",
    "https://cdn.poehali.dev/files/веретье2.JPG",
    "https://cdn.poehali.dev/files/веретье3.JPG",
    "https://cdn.poehali.dev/files/веретье5.jpg",
    "https://cdn.poehali.dev/files/веретье6.JPG",
    "https://cdn.poehali.dev/files/веретье7.JPG",
    "https://cdn.poehali.dev/files/веретье8.JPG",
    "https://cdn.poehali.dev/files/веретье9.JPG",
    "https://cdn.poehali.dev/files/веретье10.JPG",
    "https://cdn.poehali.dev/files/веретье11.JPG",
    "https://cdn.poehali.dev/files/веретье12.jpg",
    "https://cdn.poehali.dev/files/веретье13.JPG",
    "https://cdn.poehali.dev/files/веретье14.JPG",
    "https://cdn.poehali.dev/files/веретье15.JPG",
    "https://cdn.poehali.dev/files/веретье16.JPG",
    "https://cdn.poehali.dev/files/веретье17.JPG",
    "https://cdn.poehali.dev/files/веретье18.JPG",
    "https://cdn.poehali.dev/files/веретье19.JPG",
    "https://cdn.poehali.dev/files/веретье20.JPG",
    "https://cdn.poehali.dev/files/веретье21.JPG",
    "https://cdn.poehali.dev/files/веретье22.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/полазна1.JPG",
    "https://cdn.poehali.dev/files/полазна2.JPG",
    "https://cdn.poehali.dev/files/полазна3.JPG",
    "https://cdn.poehali.dev/files/полазна4.JPG",
    "https://cdn.poehali.dev/files/полазна5.JPG",
    "https://cdn.poehali.dev/files/полазна6.JPG",
    "https://cdn.poehali.dev/files/полазна7.JPG",
    "https://cdn.poehali.dev/files/полазна8.JPG",
    "https://cdn.poehali.dev/files/полазна9.JPG",
    "https://cdn.poehali.dev/files/полазна10.JPG",
    "https://cdn.poehali.dev/files/полазна11.JPG",
    "https://cdn.poehali.dev/files/полазна12.JPG",
    "https://cdn.poehali.dev/files/полазна13.JPG",
    "https://cdn.poehali.dev/files/полазна14.JPG",
    "https://cdn.poehali.dev/files/полазна15.JPG",
    "https://cdn.poehali.dev/files/полазна16.JPG",
    "https://cdn.poehali.dev/files/полазна17.JPG",
    "https://cdn.poehali.dev/files/полазна18.JPG",
    "https://cdn.poehali.dev/files/полазна19.JPG",
    "https://cdn.poehali.dev/files/полазна20.JPG",
    "https://cdn.poehali.dev/files/полазна21.JPG",
    "https://cdn.poehali.dev/files/полазна22.JPG",
    "https://cdn.poehali.dev/files/полазна23.JPG",
    "https://cdn.poehali.dev/files/полазна24.JPG",
    "https://cdn.poehali.dev/files/полазна25.JPG",
    "https://cdn.poehali.dev/files/полазна26.JPG",
    "https://cdn.poehali.dev/files/полазна27.JPG",
    "https://cdn.poehali.dev/files/полазна28.JPG",
    "https://cdn.poehali.dev/files/полазна29.JPG",
    "https://cdn.poehali.dev/files/полазна30.JPG",
    "https://cdn.poehali.dev/files/полазна31.JPG",
    "https://cdn.poehali.dev/files/полазна32.JPG",
    "https://cdn.poehali.dev/files/полазна33.JPG",
    "https://cdn.poehali.dev/files/полазна34.JPG",
    "https://cdn.poehali.dev/files/полазна35.JPG",
    "https://cdn.poehali.dev/files/полазна36.JPG",
    "https://cdn.poehali.dev/files/полазна37.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/гамы1.jpg",
    "https://cdn.poehali.dev/files/гамы2.JPG",
    "https://cdn.poehali.dev/files/гамы3.JPG",
    "https://cdn.poehali.dev/files/гамы4.JPG",
    "https://cdn.poehali.dev/files/гамы5.JPG",
    "https://cdn.poehali.dev/files/гамы6.JPG",
    "https://cdn.poehali.dev/files/гамы7.JPG",
    "https://cdn.poehali.dev/files/гамы8.JPG",
    "https://cdn.poehali.dev/files/гамы9.JPG",
    "https://cdn.poehali.dev/files/гамы10.JPG",
    "https://cdn.poehali.dev/files/гамы11.JPG",
    "https://cdn.poehali.dev/files/гамы12.JPG",
    "https://cdn.poehali.dev/files/гамы13.JPG",
    "https://cdn.poehali.dev/files/гамы14.JPG",
    "https://cdn.poehali.dev/files/гамы15.JPG",
    "https://cdn.poehali.dev/files/гамы16.JPG",
    "https://cdn.poehali.dev/files/гамы17.JPG",
    "https://cdn.poehali.dev/files/гамы18.JPG",
    "https://cdn.poehali.dev/files/гамы19.JPG",
    "https://cdn.poehali.dev/files/гамы20.JPG",
    "https://cdn.poehali.dev/files/гамы21.JPG",
    "https://cdn.poehali.dev/files/гамы22.JPG",
    "https://cdn.poehali.dev/files/гамы23.JPG",
    "https://cdn.poehali.dev/files/гамы24.JPG",
    "https://cdn.poehali.dev/files/гамы25.JPG",
    "https://cdn.poehali.dev/files/гамы26.JPG",
    "https://cdn.poehali.dev/files/гамы27.jpg",
    "https://cdn.poehali.dev/files/гамы28.jpg",
    "https://cdn.poehali.dev/files/гамы29.jpg",
    "https://cdn.poehali.dev/files/гамы30.jpg",
    "https://cdn.poehali.dev/files/гамы31.JPG",
    "https://cdn.poehali.dev/files/гамы32.JPG",
    "https://cdn.poehali.dev/files/гамы33.JPG",
    "https://cdn.poehali.dev/files/гамы34.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/ключи1.JPG",
    "https://cdn.poehali.dev/files/ключи2.JPG",
    "https://cdn.poehali.dev/files/ключи3.JPG",
    "https://cdn.poehali.dev/files/ключи4.JPG",
    "https://cdn.poehali.dev/files/ключи5.JPG",
    "https://cdn.poehali.dev/files/ключи6.JPG",
    "https://cdn.poehali.dev/files/ключи7.JPG",
    "https://cdn.poehali.dev/files/ключи8.JPG",
    "https://cdn.poehali.dev/files/ключи9.JPG",
    "https://cdn.poehali.dev/files/ключи10.JPG",
    "https://cdn.poehali.dev/files/ключи11.JPG",
    "https://cdn.poehali.dev/files/ключи12.JPG",
    "https://cdn.poehali.dev/files/ключи13.JPG",
    "https://cdn.poehali.dev/files/ключи14.JPG",
    "https://cdn.poehali.dev/files/ключи15.JPG",
    "https://cdn.poehali.dev/files/ключи16.JPG",
    "https://cdn.poehali.dev/files/ключи17.JPG",
    "https://cdn.poehali.dev/files/ключи18.JPG",
    "https://cdn.poehali.dev/files/ключи19.JPG",
    "https://cdn.poehali.dev/files/ключи20.JPG",
    "https://cdn.poehali.dev/files/ключи21.JPG",
    "https://cdn.poehali.dev/files/ключи22.JPG",
    "https://cdn.poehali.dev/files/ключи23.JPG",
    "https://cdn.poehali.dev/files/ключи24.JPG",
    "https://cdn.poehali.dev/files/ключи25.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/скобелевка1.jpg",
    "https://cdn.poehali.dev/files/скобелевка2.JPG",
    "https://cdn.poehali.dev/files/скобелевка3.jpg",
    "https://cdn.poehali.dev/files/скобелевка4.JPEG",
    "https://cdn.poehali.dev/files/скобелевка5.JPG",
    "https://cdn.poehali.dev/files/скобелевка6.JPEG",
    "https://cdn.poehali.dev/files/скобелевка7.JPG",
    "https://cdn.poehali.dev/files/скобелевка8.JPG",
    "https://cdn.poehali.dev/files/скобелевка9.JPG",
    "https://cdn.poehali.dev/files/скобелевка10.JPEG",
    "https://cdn.poehali.dev/files/скобелевка11.JPEG",
    "https://cdn.poehali.dev/files/скобелевка12.JPG",
    "https://cdn.poehali.dev/files/скобелевка13.JPG",
    "https://cdn.poehali.dev/files/скобелевка14.JPG",
    "https://cdn.poehali.dev/files/скобелевка15.JPG",
    "https://cdn.poehali.dev/files/скобелевка16.JPG",
    "https://cdn.poehali.dev/files/скобелевка17.JPG",
    "https://cdn.poehali.dev/files/скобелевка18.png",
    "https://cdn.poehali.dev/files/скобелевка19.JPG",
    "https://cdn.poehali.dev/files/скобелевка20.JPG",
    "https://cdn.poehali.dev/files/скобелевка21.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/кр.слудка1.JPG",
    "https://cdn.poehali.dev/files/кр.слудка2.JPEG",
    "https://cdn.poehali.dev/files/кр.слудка3.JPG",
    "https://cdn.poehali.dev/files/кр.слудка4.JPG",
    "https://cdn.poehali.dev/files/кр.слудка5.JPG",
    "https://cdn.poehali.dev/files/кр.слудка6.JPG",
    "https://cdn.poehali.dev/files/кр.слудка7.JPG",
    "https://cdn.poehali.dev/files/кр.слудка8.JPG",
    "https://cdn.poehali.dev/files/кр.слудка9.JPG",
    "https://cdn.poehali.dev/files/кр.слудка10.JPG",
    "https://cdn.poehali.dev/files/кр.слудка11.JPG",
    "https://cdn.poehali.dev/files/кр.слудка12.JPG",
    "https://cdn.poehali.dev/files/кр.слудка13.JPEG",
    "https://cdn.poehali.dev/files/кр.слудка14.JPG",
    "https://cdn.poehali.dev/files/кр.слудка15.JPG",
    "https://cdn.poehali.dev/files/кр.слудка16.JPG",
    "https://cdn.poehali.dev/files/кр.слудка17.JPG",
    "https://cdn.poehali.dev/files/кр.слудка18.JPG",
    "https://cdn.poehali.dev/files/кр.слудка19.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/слудка1.png",
    "https://cdn.poehali.dev/files/слудка2.jpg",
    "https://cdn.poehali.dev/files/слудка3.png",
    "https://cdn.poehali.dev/files/слудка4.png",
    "https://cdn.poehali.dev/files/слудка5.png",
    "https://cdn.poehali.dev/files/слудка6.jpg",
    "https://cdn.poehali.dev/files/слудка7.png",
    "https://cdn.poehali.dev/files/слудка8.png",
    "https://cdn.poehali.dev/files/слудка9.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/добрянка1.jpg",
    "https://cdn.poehali.dev/files/добрянка2.jpg",
    "https://cdn.poehali.dev/files/добрянка3.jpg",
    "https://cdn.poehali.dev/files/добрянка4.jpg",
    "https://cdn.poehali.dev/files/добрянка5.jpg",
    "https://cdn.poehali.dev/files/добрянка6.jpg",
    "https://cdn.poehali.dev/files/добрянка7.jpg",
    "https://cdn.poehali.dev/files/добрянка8.jpg",
    "https://cdn.poehali.dev/files/добрянка9.jpg",
    "https://cdn.poehali.dev/files/добрянка10.jpg",
    "https://cdn.poehali.dev/files/добрянка11.JPG",
    "https://cdn.poehali.dev/files/добрянка12.JPG",
    "https://cdn.poehali.dev/files/добрянка13.JPG",
    "https://cdn.poehali.dev/files/добрянка14.JPG",
    "https://cdn.poehali.dev/files/добрянка15.JPG",
    "https://cdn.poehali.dev/files/добрянка16.JPG",
    "https://cdn.poehali.dev/files/добрянка17.JPG",
    "https://cdn.poehali.dev/files/добрянка18.JPG",
    "https://cdn.poehali.dev/files/добрянка19.JPG",
    "https://cdn.poehali.dev/files/добрянка20.JPG",
    "https://cdn.poehali.dev/files/добрянка21.JPG",
    "https://cdn.poehali.dev/files/добрянка22.JPG",
    "https://cdn.poehali.dev/files/добрянка23.JPG",
    "https://cdn.poehali.dev/files/добрянка24.JPG",
    "https://cdn.poehali.dev/files/добрянка25.JPG",
    "https://cdn.poehali.dev/files/добрянка26.JPG",
    "https://cdn.poehali.dev/files/добрянка27.JPG",
    "https://cdn.poehali.dev/files/добрянка28.JPG",
    "https://cdn.poehali.dev/files/добрянка29.JPG",
    "https://cdn.poehali.dev/files/добрянка30.JPG"
  ],
  [
    "https://cdn.poehali.dev/files/400.JPG",
    "https://cdn.poehali.dev/files/402.JPG",
    "https://cdn.poehali.dev/files/403.JPG",
    "https://cdn.poehali.dev/files/404.JPG",
    "https://cdn.poehali.dev/files/405.JPG",
    "https://cdn.poehali.dev/files/406.JPG",
    "https://cdn.poehali.dev/files/407.JPG",
    "https://cdn.poehali.dev/files/408.JPG",
    "https://cdn.poehali.dev/files/409.JPG",
    "https://cdn.poehali.dev/files/410.JPG",
    "https://cdn.poehali.dev/files/411.JPG",
    "https://cdn.poehali.dev/files/412.JPG",
    "https://cdn.poehali.dev/files/413.JPG",
    "https://cdn.poehali.dev/files/414.JPG",
    "https://cdn.poehali.dev/files/415.JPG",
    "https://cdn.poehali.dev/files/416.JPG",
    "https://cdn.poehali.dev/files/417.JPG",
    "https://cdn.poehali.dev/files/418.JPG",
    "https://cdn.poehali.dev/files/419.JPG",
    "https://cdn.poehali.dev/files/420.JPG",
    "https://cdn.poehali.dev/files/421.JPG",
    "https://cdn.poehali.dev/files/422.JPG",
    "https://cdn.poehali.dev/files/423.JPG",
    "https://cdn.poehali.dev/files/424.JPG",
    "https://cdn.poehali.dev/files/425.JPG",
    "https://cdn.poehali.dev/files/426.JPG",
    "https://cdn.poehali.dev/files/427.JPG",
    "https://cdn.poehali.dev/files/428.JPG",
    "https://cdn.poehali.dev/files/429.JPG",
    "https://cdn.poehali.dev/files/430.JPG",
    "https://cdn.poehali.dev/files/431.JPG",
    "https://cdn.poehali.dev/files/432.JPG",
    "https://cdn.poehali.dev/files/433.JPG",
    "https://cdn.poehali.dev/files/434.JPG",
    "https://cdn.poehali.dev/files/435.JPG",
    "https://cdn.poehali.dev/files/436.JPG",
    "https://cdn.poehali.dev/files/437.JPG",
    "https://cdn.poehali.dev/files/438.JPG",
    "https://cdn.poehali.dev/files/439.JPG",
    "https://cdn.poehali.dev/files/440.JPG",
    "https://cdn.poehali.dev/files/441.JPG",
    "https://cdn.poehali.dev/files/442.JPG",
    "https://cdn.poehali.dev/files/443.JPG",
    "https://cdn.poehali.dev/files/444.JPG",
    "https://cdn.poehali.dev/files/445.JPG",
    "https://cdn.poehali.dev/files/446.JPG",
    "https://cdn.poehali.dev/files/447.JPG",
    "https://cdn.poehali.dev/files/448.JPG",
    "https://cdn.poehali.dev/files/449.JPG",
    "https://cdn.poehali.dev/files/450.JPG",
    "https://cdn.poehali.dev/files/451.JPG",
    "https://cdn.poehali.dev/files/452.JPG",
    "https://cdn.poehali.dev/files/453.JPG",
    "https://cdn.poehali.dev/files/454.JPG",
    "https://cdn.poehali.dev/files/455.JPG",
    "https://cdn.poehali.dev/files/456.JPG",
    "https://cdn.poehali.dev/files/457.JPG",
    "https://cdn.poehali.dev/files/458.JPG",
    "https://cdn.poehali.dev/files/459.JPG",
    "https://cdn.poehali.dev/files/460.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/600.jpg",
    "https://cdn.poehali.dev/files/601.jpg",
    "https://cdn.poehali.dev/files/602.jpg",
    "https://cdn.poehali.dev/files/603.jpg",
    "https://cdn.poehali.dev/files/604.jpg",
    "https://cdn.poehali.dev/files/605.jpg",
    "https://cdn.poehali.dev/files/606.jpg",
    "https://cdn.poehali.dev/files/607.jpg",
    "https://cdn.poehali.dev/files/608.jpg",
    "https://cdn.poehali.dev/files/609.jpg",
    "https://cdn.poehali.dev/files/610.jpg",
    "https://cdn.poehali.dev/files/611.jpg",
    "https://cdn.poehali.dev/files/612.jpg",
    "https://cdn.poehali.dev/files/613.jpg"
  ],
  [
    "https://cdn.poehali.dev/files/500.jpg",
    "https://cdn.poehali.dev/files/501.jpg",
    "https://cdn.poehali.dev/files/502.jpg",
    "https://cdn.poehali.dev/files/503.jpg",
    "https://cdn.poehali.dev/files/504.jpg",
    "https://cdn.poehali.dev/files/505.jpg",
    "https://cdn.poehali.dev/files/506.jpg",
    "https://cdn.poehali.dev/files/507.jpg",
    "https://cdn.poehali.dev/files/508.jpg",
    "https://cdn.poehali.dev/files/509.jpg",
    "https://cdn.poehali.dev/files/510.jpg",
    "https://cdn.poehali.dev/files/511.jpg",
    "https://cdn.poehali.dev/files/512.jpg",
    "https://cdn.poehali.dev/files/513.jpg",
    "https://cdn.poehali.dev/files/514.jpg",
    "https://cdn.poehali.dev/files/515.jpg"
  ]
];

export interface Project {
  img: string;
  title: string;
  size: string;
  material: string;
  location: string;
}

export const projects: Project[] = [
  {
    img: "https://cdn.poehali.dev/files/веретье0.jpg",
    title: "Баня из бревна 6×12",
    size: "6×12 м",
    material: "Оцилиндрованное бревно",
    location: 'Резиденция "Веретье", Пермский край'
  },
  {
    img: "https://cdn.poehali.dev/files/полазна1.JPG",
    title: "Баня из бруса 8×15",
    size: "8×15 м",
    material: "Профилированный брус",
    location: "п. Полазна, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/IMG_20260105_110740.jpg",
    title: "Баня из бревна 3×6",
    size: "3×6 м",
    material: "Оцилиндрованное бревно",
    location: "д. Гамы, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/ключи1.JPG",
    title: "Баня из бруса 10×10",
    size: "10×10 м",
    material: "Клееный брус",
    location: "д. Ключи, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/скобелевка1.jpg",
    title: "Баня из бревна 6×6",
    size: "6×6 м",
    material: "Ремонт парной и помывочной",
    location: "д. Скобелевка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/кр.слудка1.JPG",
    title: "Баня из бревна 6×6",
    size: "6×6 м",
    material: "Шлифовка и покраска наружных стен",
    location: "д. Красная Слудка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/слудка1.png",
    title: "Баня из бруса 6×6",
    size: "6×6 м",
    material: "Профилированный брус",
    location: "д. Красная Слудка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/добрянка1.jpg",
    title: "Баня из бруса 6×8",
    size: "6×8 м",
    material: "Брус естественной влажности",
    location: "г. Добрянка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/400.JPG",
    title: "Баня из бревна 5×5",
    size: "5×5 м",
    material: "Оцилиндрованное бревно",
    location: "п. Усть-Качка, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/600.jpg",
    title: "Баня из бревна 6×5",
    size: "6×5 м",
    material: "Рубленное бревно",
    location: "п. Троица, Пермский край"
  },
  {
    img: "https://cdn.poehali.dev/files/500.jpg",
    title: "Баня из бревна 6×8",
    size: "6×8 м",
    material: "Оцилиндрованное бревно",
    location: "д. Налимиха, Пермский край"
  }
];